# Generated by Django 5.0.6 on 2024-07-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('religion', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('residential_address', models.TextField()),
                ('permanent_home_address', models.TextField()),
                ('town_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('mobile_numbers', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_name', models.CharField(max_length=100)),
                ('nok_address', models.TextField()),
                ('nok_relationship', models.CharField(max_length=50)),
                ('nok_email_address', models.EmailField(max_length=254)),
                ('nok_mobile_numbers', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('fingerprint', models.BinaryField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
            options={
                'indexes': [models.Index(fields=['file_number'], name='data_collec_file_nu_ab823d_idx'), models.Index(fields=['surname'], name='data_collec_surname_2f73c5_idx'), models.Index(fields=['email_address'], name='data_collec_email_a_f58605_idx')],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workers', models.ManyToManyField(related_name='unions', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='data_collec_name_e88d5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank_designation', models.CharField(max_length=255)),
                ('entry_pt', models.CharField(max_length=100)),
                ('authorization', models.CharField(max_length=255)),
                ('ministry_department', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='data_collec_worker__b85170_idx'), models.Index(fields=['date'], name='data_collec_date_9022c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_department', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('to_department', models.CharField(max_length=255)),
                ('authorization', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings_transfers', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='data_collec_worker__d51aad_idx'), models.Index(fields=['date'], name='data_collec_date_ae80bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfficialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_ministry', models.CharField(max_length=100)),
                ('present_post_location', models.CharField(max_length=100)),
                ('post_work_state', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('job_class', models.CharField(blank=True, max_length=100, null=True)),
                ('lga_of_work', models.CharField(max_length=100)),
                ('present_station', models.CharField(max_length=100)),
                ('salary_group', models.CharField(max_length=100)),
                ('grade_level_step', models.CharField(max_length=100)),
                ('pay_point', models.CharField(max_length=100)),
                ('bank_verification_number', models.CharField(max_length=11, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('employment_type', models.CharField(max_length=100)),
                ('employment_status', models.CharField(max_length=100)),
                ('first_appointment_date', models.DateField()),
                ('gazette_no_ref_1', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('gazette_no_ref_2', models.CharField(blank=True, max_length=100, null=True)),
                ('last_promotion_date', models.DateField(blank=True, null=True)),
                ('gazette_no_ref_3', models.CharField(blank=True, max_length=100, null=True)),
                ('increment_date', models.DateField(blank=True, null=True)),
                ('gazette_no_ref_4', models.CharField(blank=True, max_length=100, null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_info', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='data_collec_worker__105d01_idx'), models.Index(fields=['bank_verification_number'], name='data_collec_bank_ve_ad7933_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_type', models.CharField(max_length=100)),
                ('date_of_reinstatement', models.DateField()),
                ('authorization', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='data_collec_worker__86cd1b_idx'), models.Index(fields=['leave_start_date'], name='data_collec_leave_s_6a6d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate_obtained', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='data_collection.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='data_collec_worker__82fb8b_idx'), models.Index(fields=['name'], name='data_collec_name_e541af_idx')],
            },
        ),
    ]
